# Hello carykh! Hope this helps.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        self.InputFileText = QtWidgets.QLabel(Dialog)
        self.InputFileText.setGeometry(QtCore.QRect(100, 27, 91, 16))
        self.InputFileText.setAlignment(QtCore.Qt.AlignCenter)
        self.InputFileText.setObjectName("InputFileText")
        self.InputFileDisplay = QtWidgets.QLabel(Dialog)
        self.InputFileDisplay.setGeometry(QtCore.QRect(54, 47, 191, 16))
        self.InputFileDisplay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputFileDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.InputFileDisplay.setText("")
        self.InputFileDisplay.setObjectName("InputFileDisplay")
        self.InputButton = QtWidgets.QPushButton(Dialog)
        self.InputButton.setGeometry(QtCore.QRect(30, 47, 21, 16))
        self.InputButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InputButton.setObjectName("InputButton")
        self.OutputLocationText = QtWidgets.QLabel(Dialog)
        self.OutputLocationText.setGeometry(QtCore.QRect(330, 27, 91, 16))
        self.OutputLocationText.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLocationText.setObjectName("OutputLocationText")
        self.OutputFileDisplay = QtWidgets.QLabel(Dialog)
        self.OutputFileDisplay.setGeometry(QtCore.QRect(284, 47, 191, 16))
        self.OutputFileDisplay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OutputFileDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.OutputFileDisplay.setText("")
        self.OutputFileDisplay.setObjectName("OutputFileDisplay")
        self.OutputButton = QtWidgets.QPushButton(Dialog)
        self.OutputButton.setGeometry(QtCore.QRect(260, 47, 21, 16))
        self.OutputButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OutputButton.setObjectName("OutputButton")
        self.OutputNameText = QtWidgets.QLabel(Dialog)
        self.OutputNameText.setGeometry(QtCore.QRect(170, 77, 141, 20))
        self.OutputNameText.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputNameText.setObjectName("OutputNameText")
        self.OutputNameEdit = QtWidgets.QLineEdit(Dialog)
        self.OutputNameEdit.setGeometry(QtCore.QRect(92, 97, 301, 20))
        self.OutputNameEdit.setObjectName("OutputNameEdit")
        self.ThresholdText = QtWidgets.QLabel(Dialog)
        self.ThresholdText.setGeometry(QtCore.QRect(30, 129, 91, 20))
        self.ThresholdText.setAlignment(QtCore.Qt.AlignCenter)
        self.ThresholdText.setObjectName("ThresholdText")
        self.ThresholdEdit = QtWidgets.QLineEdit(Dialog)
        self.ThresholdEdit.setGeometry(QtCore.QRect(55, 149, 41, 20))
        self.ThresholdEdit.setObjectName("ThresholdEdit")
        self.SoundedText = QtWidgets.QLabel(Dialog)
        self.SoundedText.setGeometry(QtCore.QRect(155, 129, 91, 20))
        self.SoundedText.setAlignment(QtCore.Qt.AlignCenter)
        self.SoundedText.setObjectName("SoundedText")
        self.SoundedEdit = QtWidgets.QLineEdit(Dialog)
        self.SoundedEdit.setGeometry(QtCore.QRect(180, 149, 41, 20))
        self.SoundedEdit.setText("")
        self.SoundedEdit.setObjectName("SoundedEdit")
        self.SilentSpeedEdit = QtWidgets.QLineEdit(Dialog)
        self.SilentSpeedEdit.setGeometry(QtCore.QRect(285, 149, 41, 20))
        self.SilentSpeedEdit.setText("")
        self.SilentSpeedEdit.setObjectName("SilentSpeedEdit")
        self.SilentSpeedText = QtWidgets.QLabel(Dialog)
        self.SilentSpeedText.setGeometry(QtCore.QRect(260, 129, 91, 20))
        self.SilentSpeedText.setAlignment(QtCore.Qt.AlignCenter)
        self.SilentSpeedText.setObjectName("SilentSpeedText")
        self.MarginEdit = QtWidgets.QLineEdit(Dialog)
        self.MarginEdit.setGeometry(QtCore.QRect(395, 149, 41, 20))
        self.MarginEdit.setText("")
        self.MarginEdit.setObjectName("MarginEdit")
        self.MarginText = QtWidgets.QLabel(Dialog)
        self.MarginText.setGeometry(QtCore.QRect(370, 129, 91, 20))
        self.MarginText.setAlignment(QtCore.Qt.AlignCenter)
        self.MarginText.setObjectName("MarginText")
        self.SampleInputText = QtWidgets.QLabel(Dialog)
        self.SampleInputText.setGeometry(QtCore.QRect(45, 219, 91, 20))
        self.SampleInputText.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleInputText.setObjectName("SampleInputText")
        self.SampleInputEdit = QtWidgets.QLineEdit(Dialog)
        self.SampleInputEdit.setGeometry(QtCore.QRect(70, 239, 41, 20))
        self.SampleInputEdit.setObjectName("SampleInputEdit")
        self.SampleOutputEdit = QtWidgets.QLineEdit(Dialog)
        self.SampleOutputEdit.setGeometry(QtCore.QRect(158, 239, 41, 20))
        self.SampleOutputEdit.setText("")
        self.SampleOutputEdit.setObjectName("SampleOutputEdit")
        self.SampleOutputText = QtWidgets.QLabel(Dialog)
        self.SampleOutputText.setGeometry(QtCore.QRect(133, 219, 91, 20))
        self.SampleOutputText.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleOutputText.setObjectName("SampleOutputText")
        self.SampleText = QtWidgets.QLabel(Dialog)
        self.SampleText.setGeometry(QtCore.QRect(90, 199, 91, 20))
        self.SampleText.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleText.setObjectName("SampleText")
        self.FrameRateText = QtWidgets.QLabel(Dialog)
        self.FrameRateText.setGeometry(QtCore.QRect(320, 199, 91, 20))
        self.FrameRateText.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameRateText.setObjectName("FrameRateText")
        self.FrameRateOutputEdit = QtWidgets.QLineEdit(Dialog)
        self.FrameRateOutputEdit.setGeometry(QtCore.QRect(392, 239, 41, 20))
        self.FrameRateOutputEdit.setText("")
        self.FrameRateOutputEdit.setObjectName("FrameRateOutputEdit")
        self.FrameRateInputEdit = QtWidgets.QLineEdit(Dialog)
        self.FrameRateInputEdit.setGeometry(QtCore.QRect(295, 239, 41, 20))
        self.FrameRateInputEdit.setObjectName("FrameRateInputEdit")
        self.FrameRateInputText = QtWidgets.QLabel(Dialog)
        self.FrameRateInputText.setGeometry(QtCore.QRect(270, 219, 91, 20))
        self.FrameRateInputText.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameRateInputText.setObjectName("FrameRateInputText")
        self.FrameRateOutputText = QtWidgets.QLabel(Dialog)
        self.FrameRateOutputText.setGeometry(QtCore.QRect(367, 219, 91, 20))
        self.FrameRateOutputText.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameRateOutputText.setObjectName("FrameRateOutputText")
        self.FrameQualityText = QtWidgets.QLabel(Dialog)
        self.FrameQualityText.setGeometry(QtCore.QRect(210, 269, 91, 20))
        self.FrameQualityText.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameQualityText.setObjectName("FrameQualityText")
        self.FrameQualityBox = QtWidgets.QComboBox(Dialog)
        self.FrameQualityBox = setPlaceholderText("3")
        self.FrameQualityBox.setGeometry(QtCore.QRect(240, 289, 31, 22))
        self.FrameQualityBox.setObjectName("FrameQualityBox")
        self.FrameQualityBox.addItem("")
        self.FrameQualityBox.addItem("")
        self.FrameQualityBox.addItem("")
        self.FrameQualityBox.addItem("")
        self.FrameQualityBox.addItem("")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(86, 201, 20, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(164, 201, 16, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(79, 210, 16, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(173, 210, 16, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.InputComment = QtWidgets.QLabel(Dialog)
        self.InputComment.setGeometry(QtCore.QRect(20, 329, 451, 16))
        self.InputComment.setObjectName("InputComment")
        self.OutputLocationComment = QtWidgets.QLabel(Dialog)
        self.OutputLocationComment.setGeometry(QtCore.QRect(20, 349, 451, 16))
        self.OutputLocationComment.setObjectName("OutputLocationComment")
        self.OutputNameComment = QtWidgets.QLabel(Dialog)
        self.OutputNameComment.setGeometry(QtCore.QRect(20, 369, 451, 16))
        self.OutputNameComment.setObjectName("OutputNameComment")
        self.ThresholdComment1 = QtWidgets.QLabel(Dialog)
        self.ThresholdComment1.setGeometry(QtCore.QRect(20, 389, 451, 16))
        self.ThresholdComment1.setObjectName("ThresholdComment1")
        self.ThresholdComment2 = QtWidgets.QLabel(Dialog)
        self.ThresholdComment2.setGeometry(QtCore.QRect(102, 401, 361, 20))
        self.ThresholdComment2.setObjectName("ThresholdComment2")
        self.SoundedComment = QtWidgets.QLabel(Dialog)
        self.SoundedComment.setGeometry(QtCore.QRect(20, 425, 451, 16))
        self.SoundedComment.setObjectName("SoundedComment")
        self.SilentSpeedComment = QtWidgets.QLabel(Dialog)
        self.SilentSpeedComment.setGeometry(QtCore.QRect(20, 449, 451, 16))
        self.SilentSpeedComment.setObjectName("SilentSpeedComment")
        self.MarginComment1 = QtWidgets.QLabel(Dialog)
        self.MarginComment1.setGeometry(QtCore.QRect(20, 469, 461, 16))
        self.MarginComment1.setObjectName("MarginComment1")
        self.MarginComment2 = QtWidgets.QLabel(Dialog)
        self.MarginComment2.setGeometry(QtCore.QRect(92, 482, 361, 20))
        self.MarginComment2.setObjectName("MarginComment2")
        self.MarginComment3 = QtWidgets.QLabel(Dialog)
        self.MarginComment3.setGeometry(QtCore.QRect(92, 497, 361, 20))
        self.MarginComment3.setObjectName("MarginComment3")
        self.SampleComment = QtWidgets.QLabel(Dialog)
        self.SampleComment.setGeometry(QtCore.QRect(20, 517, 451, 16))
        self.SampleComment.setObjectName("SampleComment")
        self.FrameRateComment = QtWidgets.QLabel(Dialog)
        self.FrameRateComment.setGeometry(QtCore.QRect(20, 537, 451, 16))
        self.FrameRateComment.setObjectName("FrameRateComment")
        self.FrameQualityComment = QtWidgets.QLabel(Dialog)
        self.FrameQualityComment.setGeometry(QtCore.QRect(20, 557, 451, 16))
        self.FrameQualityComment.setObjectName("FrameQualityComment")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(392, 201, 21, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(406, 210, 16, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(309, 209, 16, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(318, 200, 20, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.JumpCutButton = QtWidgets.QPushButton(Dialog)
        self.JumpCutButton.setGeometry(QtCore.QRect(350, 290, 75, 23))
        self.JumpCutButton.setObjectName("JumpCutButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.InputFileText.setText(_translate("Dialog", "Input file location"))
        self.InputButton.setText(_translate("Dialog", "..."))
        self.OutputLocationText.setText(_translate("Dialog", "Output file location"))
        self.OutputButton.setText(_translate("Dialog", "..."))
        self.OutputNameText.setText(_translate("Dialog", "(Optional) Output file name"))
        self.ThresholdText.setText(_translate("Dialog", "Silent threshold"))
        self.SoundedText.setText(_translate("Dialog", "Sounded speed"))
        self.SilentSpeedText.setText(_translate("Dialog", "Silent speed"))
        self.MarginText.setText(_translate("Dialog", "Frame margin"))
        self.SampleInputText.setText(_translate("Dialog", "Input"))
        self.SampleOutputText.setText(_translate("Dialog", "Output"))
        self.SampleText.setText(_translate("Dialog", "Sample rate"))
        self.FrameRateText.setText(_translate("Dialog", "Frame rate"))
        self.FrameRateInputText.setText(_translate("Dialog", "Input"))
        self.FrameRateOutputText.setText(_translate("Dialog", "Output"))
        self.FrameQualityText.setText(_translate("Dialog", "Frame quality"))
        self.FrameQualityBox.setItemText(0, _translate("Dialog", "1"))
        self.FrameQualityBox.setItemText(1, _translate("Dialog", "2"))
        self.FrameQualityBox.setItemText(2, _translate("Dialog", "3"))
        self.FrameQualityBox.setItemText(3, _translate("Dialog", "4"))
        self.FrameQualityBox.setItemText(4, _translate("Dialog", "5"))
        self.InputComment.setText(_translate("Dialog", "Input file location: The video file you want modified."))
        self.OutputLocationComment.setText(_translate("Dialog", "Output file location: Where you want the modified video to be."))
        self.OutputNameComment.setText(_translate("Dialog", "Output file name: Optional. if not included, it\'ll just modify the input file name"))
        self.ThresholdComment1.setText(_translate("Dialog", "Silent threshold: The volume amount that frames\' audio needs to surpass"))
        self.ThresholdComment2.setText(_translate("Dialog", "to be consider \"sounded\". It ranges from 0 (silence) to 1 (max volume)"))
        self.SoundedComment.setText(_translate("Dialog", "Sounded speed: The speed that sounded (spoken) frames should be played at. Typically 1."))
        self.SilentSpeedComment.setText(_translate("Dialog", "Silent speed: The speed that silent frames should be played at. 999999 For jumpcutting."))
        self.MarginComment1.setText(_translate("Dialog", "Frame margin: Some silent frames adjacent to sounded frames are included to prodive context."))
        self.MarginComment2.setText(_translate("Dialog", "How many frames on either the side of speech should be included?"))
        self.MarginComment3.setText(_translate("Dialog", "That\'s this variable."))
        self.SampleComment.setText(_translate("Dialog", "Sample rate: Sample rate of the input and output videos"))
        self.FrameRateComment.setText(_translate("Dialog", "Frame rate: Frame rate of the input and output videos. optional"))
        self.FrameQualityComment.setText(_translate("Dialog", "Frame quality: Quality of frames to be extracted from input video. Range: (1-5), (3 default)."))
        self.JumpCutButton.setText(_translate("Dialog", "Jump-cut"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

